name: Node CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy billing app
        run: |
          cd /home/silicon/Documents/project/billing-system
          git pull origin main
          docker compose down
          docker compose up --build -d
          docker ps
